name: Debug

on:
  - push

jobs:
  debug:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    steps:
      - name: Install Incus
        run: |
          sudo apt update
          sudo apt install -y -V incus
      - name: incus config device
        run: |
          set -x
          # mkdir -m 777 logs
          sudo incus admin init --auto
          if [ "${{ matrix.os }}" = "ubuntu-24.04-arm" ]; then
            sudo incus launch --quiet images:ubuntu/noble/arm64 target
          else
            sudo incus launch --quiet images:ubuntu/noble target
          fi
          sudo incus config device add target host-rw disk source=$PWD path=/host-rw
          sudo incus exec target --user $(sudo id -u) -- mkdir -p /host-rw/logs/aaa
